TRAIN_DATA = [
    ("Joe Biden signed an executive order on climate change.", {"entities": [(0, 9, "POLITICIAN")]}),
    ("Vladimir Putin met with Chinese diplomats yesterday.", {"entities": [(0, 14, "POLITICIAN")]}),
    ("Angela Merkel retired from politics after 16 years as Chancellor.", {"entities": [(0, 13, "POLITICIAN")]}),
    ("Emmanuel Macron faced criticism over pension reforms.", {"entities": [(0, 15, "POLITICIAN")]}),
    ("Justin Trudeau announced new environmental policies.", {"entities": [(0, 14, "POLITICIAN")]}),
    ("Boris Johnson resigned as Prime Minister in 2022.", {"entities": [(0, 13, "POLITICIAN")]}),
    ("Narendra Modi visited the United States last month.", {"entities": [(0, 13, "POLITICIAN")]}),
    ("Xi Jinping emphasized China's economic growth targets.", {"entities": [(0, 10, "POLITICIAN")]}),
    ("Kamala Harris became the first female Vice President of the US.", {"entities": [(0, 13, "POLITICIAN")]}),
    ("Alexandria Ocasio-Cortez proposed a new climate bill.", {"entities": [(0, 26, "POLITICIAN")]}),
    ("Senator Elizabeth Warren questioned bank executives during the hearing.", {"entities": [(8, 24, "POLITICIAN")]}),
    ("President Volodymyr Zelensky addressed the nation about security concerns.", {"entities": [(10, 30, "POLITICIAN")]}),
    ("Keir Starmer won the Labour leadership election.", {"entities": [(0, 12, "POLITICIAN")]}),
    ("Chancellor Olaf Scholz visited Berlin's new tech hub.", {"entities": [(11, 22, "POLITICIAN")]}),
    ("Prime Minister Jacinda Ardern resigned from her position.", {"entities": [(14, 28, "POLITICIAN")]}),
    ("Rishi Sunak announced a new economic plan for the UK.", {"entities": [(0, 11, "POLITICIAN")]}),
    ("Anthony Albanese won the Australian election in 2022.", {"entities": [(0, 18, "POLITICIAN")]}),
    ("Vice President Mike Pence chaired the committee meeting.", {"entities": [(14, 24, "POLITICIAN")]}),
    ("Sadiq Khan introduced new policies for London transport.", {"entities": [(0, 10, "POLITICIAN")]}),
    ("Bernie Sanders campaigned for universal healthcare.", {"entities": [(0, 14, "POLITICIAN")]}),
    
    ("Beyoncé released a new album to critical acclaim.", {"entities": [(0, 7, "CELEBRITY")]}),
    ("Leonardo DiCaprio starred in a climate change documentary.", {"entities": [(0, 17, "CELEBRITY")]}),
    ("Taylor Swift broke ticket sales records with her new tour.", {"entities": [(0, 12, "CELEBRITY")]}),
    ("Dwayne Johnson announced his new fitness app.", {"entities": [(0, 15, "CELEBRITY")]}),
    ("Oprah Winfrey interviewed the controversial author.", {"entities": [(0, 13, "CELEBRITY")]}),
    ("Brad Pitt won an Academy Award for his performance.", {"entities": [(0, 9, "CELEBRITY")]}),
    ("Rihanna expanded her fashion and beauty empire.", {"entities": [(0, 7, "CELEBRITY")]}),
    ("Tom Hanks will star in the upcoming historical drama.", {"entities": [(0, 9, "CELEBRITY")]}),
    ("Jennifer Lopez canceled her concert due to illness.", {"entities": [(0, 14, "CELEBRITY")]}),
    ("Robert Downey Jr. invested in green technology startups.", {"entities": [(0, 17, "CELEBRITY")]}),
    ("Lady Gaga performed at the presidential inauguration.", {"entities": [(0, 9, "CELEBRITY")]}),
    ("Will Smith faced backlash after the awards ceremony incident.", {"entities": [(0, 10, "CELEBRITY")]}),
    ("Meryl Streep joined the cast of the acclaimed series.", {"entities": [(0, 12, "CELEBRITY")]}),
    ("Justin Bieber postponed his world tour for health reasons.", {"entities": [(0, 13, "CELEBRITY")]}),
    ("Serena Williams announced her retirement from professional tennis.", {"entities": [(0, 15, "CELEBRITY")]}),
    ("Ryan Reynolds launched a new marketing campaign for his gin brand.", {"entities": [(0, 13, "CELEBRITY")]}),
    ("Adele swept the Grammy Awards with her latest album.", {"entities": [(0, 5, "CELEBRITY")]}),
    ("Cristiano Ronaldo transferred to a Saudi Arabian club.", {"entities": [(0, 17, "CELEBRITY")]}),
    ("Ellen DeGeneres ended her long-running talk show.", {"entities": [(0, 16, "CELEBRITY")]}),
    ("Kanye West changed his legal name to Ye.", {"entities": [(0, 10, "CELEBRITY")]}),
    
    ("The bank robbery resulted in a citywide police search.", {"entities": [(4, 16, "CRIME")]}),
    ("Identity theft cases increased by 30% last year.", {"entities": [(0, 14, "CRIME")]}),
    ("Cyberbullying has become more prevalent among teenagers.", {"entities": [(0, 13, "CRIME")]}),
    ("Money laundering operations were uncovered across three countries.", {"entities": [(0, 16, "CRIME")]}),
    ("Tax evasion charges were filed against the corporation.", {"entities": [(0, 11, "CRIME")]}),
    ("The murder investigation focused on forensic evidence.", {"entities": [(4, 10, "CRIME")]}),
    ("Wire fraud schemes targeted elderly citizens.", {"entities": [(0, 10, "CRIME")]}),
    ("Insider trading led to the executive's arrest.", {"entities": [(0, 15, "CRIME")]}),
    ("Drug trafficking networks operate across international borders.", {"entities": [(0, 16, "CRIME")]}),
    ("Embezzlement of company funds went undetected for years.", {"entities": [(0, 12, "CRIME")]}),
    ("The assault occurred outside a downtown nightclub.", {"entities": [(4, 11, "CRIME")]}),
    ("Corporate espionage cost the company millions in lost patents.", {"entities": [(0, 19, "CRIME")]}),
    ("Bribery allegations surfaced during the government investigation.", {"entities": [(0, 7, "CRIME")]}),
    ("Blackmail attempts were reported to authorities.", {"entities": [(0, 9, "CRIME")]}),
    ("Counterfeiting operations were dismantled by federal agents.", {"entities": [(0, 14, "CRIME")]}),
    ("Arson was suspected in the warehouse fire.", {"entities": [(0, 5, "CRIME")]}),
    ("Human trafficking victims were rescued in the police operation.", {"entities": [(0, 17, "CRIME")]}),
    ("Extortion threats were sent to multiple business owners.", {"entities": [(0, 9, "CRIME")]}),
    ("Vandalism at the historic site caused irreparable damage.", {"entities": [(0, 9, "CRIME")]}),
    ("Forgery of official documents led to the arrest.", {"entities": [(0, 7, "CRIME")]}),
    
    ("Smith v. Jones will be heard by the Supreme Court.", {"entities": [(0, 13, "COURT_CASE")]}),
    ("Brown v. Board of Education changed American education.", {"entities": [(0, 27, "COURT_CASE")]}),
    ("Roe v. Wade was overturned by a Supreme Court decision.", {"entities": [(0, 11, "COURT_CASE")]}),
    ("United States v. Microsoft settled antitrust allegations.", {"entities": [(0, 25, "COURT_CASE")]}),
    ("Miranda v. Arizona established important rights for the accused.", {"entities": [(0, 18, "COURT_CASE")]}),
    ("Plessy v. Ferguson upheld segregation laws until 1954.", {"entities": [(0, 19, "COURT_CASE")]}),
    ("The verdict in Citizens United v. FEC changed campaign finance rules.", {"entities": [(13, 32, "COURT_CASE")]}),
    ("Bush v. Gore decided the 2000 presidential election.", {"entities": [(0, 13, "COURT_CASE")]}),
    ("Obergefell v. Hodges legalized same-sex marriage nationwide.", {"entities": [(0, 20, "COURT_CASE")]}),
    ("The McDonald v. Chicago ruling addressed Second Amendment rights.", {"entities": [(4, 22, "COURT_CASE")]}),
    ("District of Columbia v. Heller was a landmark gun rights case.", {"entities": [(0, 28, "COURT_CASE")]}),
    ("Gideon v. Wainwright guaranteed the right to an attorney.", {"entities": [(0, 20, "COURT_CASE")]}),
    ("New York Times v. Sullivan set standards for press freedom.", {"entities": [(0, 25, "COURT_CASE")]}),
    ("Tinker v. Des Moines protected student speech rights.", {"entities": [(0, 20, "COURT_CASE")]}),
    ("Loving v. Virginia struck down bans on interracial marriage.", {"entities": [(0, 17, "COURT_CASE")]}),
    ("Marbury v. Madison established judicial review.", {"entities": [(0, 18, "COURT_CASE")]}),
    ("Korematsu v. United States allowed Japanese internment camps.", {"entities": [(0, 26, "COURT_CASE")]}),
    ("Mapp v. Ohio established the exclusionary rule in evidence.", {"entities": [(0, 12, "COURT_CASE")]}),
    ("The ruling in Shelby County v. Holder affected voting rights.", {"entities": [(13, 34, "COURT_CASE")]}),
    ("The Texas v. Johnson decision protected flag burning as speech.", {"entities": [(4, 18, "COURT_CASE")]}),
    
    ("The Vietnam War lasted from 1955 to 1975.", {"entities": [(4, 16, "MILITARY_CONFLICT")]}),
    ("World War II ended with Japan's surrender in 1945.", {"entities": [(0, 12, "MILITARY_CONFLICT")]}),
    ("The Korean War resulted in the division of the peninsula.", {"entities": [(4, 15, "MILITARY_CONFLICT")]}),
    ("The Iraq War began with the US invasion in 2003.", {"entities": [(4, 12, "MILITARY_CONFLICT")]}),
    ("The Syrian Civil War has displaced millions of people.", {"entities": [(4, 21, "MILITARY_CONFLICT")]}),
    ("The Gulf War was a response to Iraq's invasion of Kuwait.", {"entities": [(4, 13, "MILITARY_CONFLICT")]}),
    ("The Falklands War was fought between Argentina and the UK.", {"entities": [(4, 18, "MILITARY_CONFLICT")]}),
    ("The Afghanistan War became America's longest military engagement.", {"entities": [(4, 20, "MILITARY_CONFLICT")]}),
    ("The Bosnian War led to the breakup of Yugoslavia.", {"entities": [(4, 16, "MILITARY_CONFLICT")]}),
    ("The Six-Day War changed Middle Eastern borders.", {"entities": [(4, 16, "MILITARY_CONFLICT")]}),
    ("The American Civil War divided the nation from 1861 to 1865.", {"entities": [(4, 22, "MILITARY_CONFLICT")]}),
    ("The Crimean War involved Russia, Britain, France, and the Ottoman Empire.", {"entities": [(4, 16, "MILITARY_CONFLICT")]}),
    ("The Russo-Ukrainian War escalated in February 2022.", {"entities": [(4, 23, "MILITARY_CONFLICT")]}),
    ("The Yemen Civil War created a humanitarian crisis.", {"entities": [(4, 19, "MILITARY_CONFLICT")]}),
    ("The Indo-Pakistani War of 1971 led to Bangladesh's independence.", {"entities": [(4, 29, "MILITARY_CONFLICT")]}),
    ("The Israel-Hamas War intensified regional tensions.", {"entities": [(4, 20, "MILITARY_CONFLICT")]}),
    ("The Balkan Wars preceded World War I.", {"entities": [(4, 16, "MILITARY_CONFLICT")]}),
    ("The Napoleonic Wars reshaped European borders.", {"entities": [(4, 20, "MILITARY_CONFLICT")]}),
    ("The Congo War involved multiple African nations.", {"entities": [(4, 14, "MILITARY_CONFLICT")]}),
    ("The Arab-Israeli War of 1948 followed Israeli independence.", {"entities": [(4, 29, "MILITARY_CONFLICT")]}),
    
    ("Black Lives Matter protests spread across major cities.", {"entities": [(0, 17, "SOCIAL_MOVEMENT")]}),
    ("The Me Too movement exposed widespread sexual harassment.", {"entities": [(4, 16, "SOCIAL_MOVEMENT")]}),
    ("Fridays for Future organized climate strikes globally.", {"entities": [(0, 18, "SOCIAL_MOVEMENT")]}),
    ("The Civil Rights Movement fought for racial equality.", {"entities": [(4, 25, "SOCIAL_MOVEMENT")]}),
    ("The Women's Suffrage Movement secured voting rights.", {"entities": [(4, 28, "SOCIAL_MOVEMENT")]}),
    ("Occupy Wall Street protested economic inequality.", {"entities": [(0, 18, "SOCIAL_MOVEMENT")]}),
    ("The Gay Rights Movement achieved significant legal victories.", {"entities": [(4, 23, "SOCIAL_MOVEMENT")]}),
    ("The Arab Spring uprisings spread across the Middle East.", {"entities": [(4, 15, "SOCIAL_MOVEMENT")]}),
    ("The Labor Movement fought for workers' rights and protections.", {"entities": [(4, 18, "SOCIAL_MOVEMENT")]}),
    ("The Environmental Movement raised awareness about climate change.", {"entities": [(4, 26, "SOCIAL_MOVEMENT")]}),
    ("The Anti-Apartheid Movement pressured South Africa to change.", {"entities": [(4, 26, "SOCIAL_MOVEMENT")]}),
    ("The Disability Rights Movement secured legal protections.", {"entities": [(4, 29, "SOCIAL_MOVEMENT")]}),
    ("The Tea Party Movement influenced American conservative politics.", {"entities": [(4, 22, "SOCIAL_MOVEMENT")]}),
    ("The Anti-War Movement opposed American involvement in Vietnam.", {"entities": [(4, 20, "SOCIAL_MOVEMENT")]}),
    ("The Indian Independence Movement led by Gandhi achieved freedom from British rule.", {"entities": [(4, 32, "SOCIAL_MOVEMENT")]}),
    ("The Prison Reform Movement advocates for humane treatment.", {"entities": [(4, 27, "SOCIAL_MOVEMENT")]}),
    ("The Pro-Choice Movement defends abortion rights.", {"entities": [(4, 23, "SOCIAL_MOVEMENT")]}),
    ("The Fair Housing Movement fights against discrimination.", {"entities": [(4, 25, "SOCIAL_MOVEMENT")]}),
    ("The Animal Rights Movement opposes animal testing.", {"entities": [(4, 26, "SOCIAL_MOVEMENT")]}),
    ("The Indigenous Rights Movement works to protect native lands.", {"entities": [(4, 29, "SOCIAL_MOVEMENT")]}),
    
    ("Bitcoin fell below $30,000 after the market crash.", {"entities": [(0, 7, "CURRENCY")]}),
    ("The Euro strengthened against the dollar last quarter.", {"entities": [(4, 8, "CURRENCY")]}),
    ("Japanese Yen weakened due to economic policies.", {"entities": [(0, 12, "CURRENCY")]}),
    ("Ethereum's price volatility attracted speculative investors.", {"entities": [(0, 8, "CURRENCY")]}),
    ("The British Pound dropped after the Brexit vote.", {"entities": [(4, 17, "CURRENCY")]}),
    ("Chinese Yuan devaluation impacted global markets.", {"entities": [(0, 12, "CURRENCY")]}),
    ("Dogecoin surged following celebrity endorsements.", {"entities": [(0, 8, "CURRENCY")]}),
    ("Swiss Franc remains a safe-haven currency during crises.", {"entities": [(0, 11, "CURRENCY")]}),
    ("Russian Ruble depreciated amid international sanctions.", {"entities": [(0, 13, "CURRENCY")]}),
    ("Cardano implemented new blockchain features.", {"entities": [(0, 7, "CURRENCY")]}),
    ("Indian Rupee hit record lows against the dollar.", {"entities": [(0, 12, "CURRENCY")]}),
    ("Solana gained popularity in the DeFi ecosystem.", {"entities": [(0, 6, "CURRENCY")]}),
    ("Mexican Peso strengthened after the trade agreement.", {"entities": [(0, 12, "CURRENCY")]}),
    ("Litecoin transactions increased by 25% this quarter.", {"entities": [(0, 8, "CURRENCY")]}),
    ("Brazilian Real fluctuated due to political uncertainty.", {"entities": [(0, 13, "CURRENCY")]}),
    ("Ripple faced regulatory challenges in multiple countries.", {"entities": [(0, 6, "CURRENCY")]}),
    ("South Korean Won gained after positive economic data.", {"entities": [(0, 16, "CURRENCY")]}),
    ("Tether maintains its peg to the US dollar.", {"entities": [(0, 6, "CURRENCY")]}),
    ("Australian Dollar reached a six-month high.", {"entities": [(0, 17, "CURRENCY")]}),
    ("Polkadot introduced cross-chain interoperability.", {"entities": [(0, 8, "CURRENCY")]}),
    
    ("The Microsoft-Activision merger faced regulatory scrutiny.", {"entities": [(4, 27, "MERGER_ACQUISITION")]}),
    ("Amazon's acquisition of MGM expanded its content library.", {"entities": [(10, 28, "MERGER_ACQUISITION")]}),
    ("The Disney-Fox merger transformed the entertainment industry.", {"entities": [(4, 20, "MERGER_ACQUISITION")]}),
    ("Google's acquisition of Fitbit raised privacy concerns.", {"entities": [(10, 31, "MERGER_ACQUISITION")]}),
    ("The T-Mobile-Sprint merger reduced wireless carriers to three.", {"entities": [(4, 25, "MERGER_ACQUISITION")]}),
    ("Facebook's acquisition of Instagram proved highly profitable.", {"entities": [(12, 36, "MERGER_ACQUISITION")]}),
    ("The AT&T-Time Warner merger was approved after appeals.", {"entities": [(4, 26, "MERGER_ACQUISITION")]}),
    ("Salesforce's acquisition of Slack cost $27.7 billion.", {"entities": [(14, 32, "MERGER_ACQUISITION")]}),
    ("The Exxon-Mobil merger created an energy giant.", {"entities": [(4, 21, "MERGER_ACQUISITION")]}),
    ("Microsoft's acquisition of LinkedIn expanded its professional network.", {"entities": [(13, 36, "MERGER_ACQUISITION")]}),
    ("The Bayer-Monsanto merger faced antitrust concerns.", {"entities": [(4, 24, "MERGER_ACQUISITION")]}),
    ("CVS's acquisition of Aetna combined pharmacy and insurance.", {"entities": [(7, 24, "MERGER_ACQUISITION")]}),
    ("The Pfizer-Wyeth merger was worth $68 billion.", {"entities": [(4, 22, "MERGER_ACQUISITION")]}),
    ("Disney's acquisition of Lucasfilm brought Star Wars to the company.", {"entities": [(10, 33, "MERGER_ACQUISITION")]}),
    ("The Comcast-NBCUniversal merger changed media distribution.", {"entities": [(4, 31, "MERGER_ACQUISITION")]}),
    ("Oracle's acquisition of Sun Microsystems expanded its server business.", {"entities": [(10, 39, "MERGER_ACQUISITION")]}),
    ("The United-Continental merger created a major airline.", {"entities": [(4, 28, "MERGER_ACQUISITION")]}),
    ("Apple's acquisition of Beats strengthened its audio products.", {"entities": [(9, 28, "MERGER_ACQUISITION")]}),
    ("The HP-Compaq merger faced shareholder resistance.", {"entities": [(4, 19, "MERGER_ACQUISITION")]}),
    ("Intel's acquisition of Mobileye focused on autonomous driving technology.", {"entities": [(9, 32, "MERGER_ACQUISITION")]}),
    
    ("The hurricane devastated coastal communities.", {"entities": [(4, 13, "NATURAL_DISASTER")]}),
    ("An earthquake measuring 7.2 struck the region.", {"entities": [(3, 13, "NATURAL_DISASTER")]}),
    ("The tsunami killed thousands across multiple countries.", {"entities": [(4, 11, "NATURAL_DISASTER")]}),
    ("Wildfires spread rapidly due to drought conditions.", {"entities": [(0, 9, "NATURAL_DISASTER")]}),
    ("The tornado destroyed hundreds of homes in the Midwest.", {"entities": [(4, 11, "NATURAL_DISASTER")]}),
    ("Severe flooding forced evacuations in low-lying areas.", {"entities": [(7, 15, "NATURAL_DISASTER")]}),
    ("The typhoon caused power outages across the island.", {"entities": [(4, 11, "NATURAL_DISASTER")]}),
    ("A volcanic eruption spewed ash into the atmosphere.", {"entities": [(2, 19, "NATURAL_DISASTER")]}),
    ("The drought led to crop failures and water restrictions.", {"entities": [(4, 11, "NATURAL_DISASTER")]}),
    ("A landslide buried the mountain village after heavy rains.", {"entities": [(2, 11, "NATURAL_DISASTER")]}),
    ("The blizzard shut down transportation across the Northeast.", {"entities": [(4, 12, "NATURAL_DISASTER")]}),
    ("An avalanche trapped skiers on the mountain slope.", {"entities": [(3, 12, "NATURAL_DISASTER")]}),
    ("The cyclone's path threatened coastal communities.", {"entities": [(4, 11, "NATURAL_DISASTER")]}),
    ("Extreme heat waves broke temperature records.", {"entities": [(9, 14, "NATURAL_DISASTER")]}),
    ("The mudslide destroyed infrastructure after torrential rain.", {"entities": [(4, 12, "NATURAL_DISASTER")]}),
    ("Severe hailstorms damaged crops throughout the region.", {"entities": [(7, 17, "NATURAL_DISASTER")]}),
    ("The famine affected millions in drought-stricken areas.", {"entities": [(4, 10, "NATURAL_DISASTER")]}),
    ("A dust storm reduced visibility on the highway.", {"entities": [(2, 12, "NATURAL_DISASTER")]}),
    ("The flash flood washed away bridges and roads.", {"entities": [(4, 15, "NATURAL_DISASTER")]}),
    ("A sinkhole suddenly appeared in the middle of the street.", {"entities": [(2, 10, "NATURAL_DISASTER")]}),
    
    ("The S&P 500 reached an all-time high yesterday.", {"entities": [(4, 11, "STOCK_MARKET_INDEX")]}),
    ("Dow Jones Industrial Average fell 2% on recession fears.", {"entities": [(0, 29, "STOCK_MARKET_INDEX")]}),
    ("The NASDAQ Composite gained 150 points in today's trading.", {"entities": [(4, 21, "STOCK_MARKET_INDEX")]}),
    ("FTSE 100 companies reported stronger than expected earnings.", {"entities": [(0, 8, "STOCK_MARKET_INDEX")]}),
    ("The Nikkei 225 dropped after the central bank announcement.", {"entities": [(4, 14, "STOCK_MARKET_INDEX")]}),
    ("DAX index rose as German economic outlook improved.", {"entities": [(0, 9, "STOCK_MARKET_INDEX")]}),
    ("The Hang Seng Index declined amid regulatory concerns.", {"entities": [(4, 20, "STOCK_MARKET_INDEX")]}),
    ("Shanghai Composite closed up 1.2% on stimulus hopes.", {"entities": [(0, 19, "STOCK_MARKET_INDEX")]}),
    ("The CAC 40 outperformed other European indices.", {"entities": [(4, 10, "STOCK_MARKET_INDEX")]}),
    ("Russell 2000 small-cap stocks showed volatility.", {"entities": [(0, 12, "STOCK_MARKET_INDEX")]}),
    ("The KOSPI reached new heights on semiconductor strength.", {"entities": [(4, 9, "STOCK_MARKET_INDEX")]}),
    ("ASX 200 fell following the central bank's interest rate decision.", {"entities": [(0, 7, "STOCK_MARKET_INDEX")]}),
    ("The BSE Sensex crossed the 60,000 mark for the first time.", {"entities": [(4, 14, "STOCK_MARKET_INDEX")]}),
    ("IBEX 35 companies announced dividend increases.", {"entities": [(0, 7, "STOCK_MARKET_INDEX")]}),
    ("The TSX Composite gained on rising commodity prices.", {"entities": [(4, 17, "STOCK_MARKET_INDEX")]}),
    ("Euro Stoxx 50 declined after disappointing economic data.", {"entities": [(0, 14, "STOCK_MARKET_INDEX")]}),
    ("The Wilshire 5000 provides the broadest market measure.", {"entities": [(4, 17, "STOCK_MARKET_INDEX")]}),
    ("MSCI World Index tracks developed market performance.", {"entities": [(0, 16, "STOCK_MARKET_INDEX")]}),
    ("The FTSE MIB represents Italy's leading companies.", {"entities": [(4, 12, "STOCK_MARKET_INDEX")]}),
    ("TOPIX broadly measures Japanese market performance.", {"entities": [(0, 5, "STOCK_MARKET_INDEX")]}),
    
    ("AAPL shares hit a record high after earnings.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    ("MSFT announced a stock buyback program.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    ("TSLA volatility increased after the CEO's tweets.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    ("AMZN faced regulatory scrutiny in multiple markets.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    ("GOOGL introduced new AI features for its products.", {"entities": [(0, 5, "STOCK_SYMBOL")]}),
    ("FB rebranded as META to reflect its new focus.", {"entities": [(0, 2, "STOCK_SYMBOL")]}),
    ("NFLX subscribers grew despite increased competition.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    ("JPM increased its dividend by 5% annually.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("BAC reported strong quarterly results.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("JNJ vaccine received regulatory approval.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("WMT expanded its e-commerce capabilities.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("PFE announced a breakthrough in cancer treatment.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("KO introduced new beverage products globally.", {"entities": [(0, 2, "STOCK_SYMBOL")]}),
    ("DIS streaming service exceeded subscriber projections.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("XOM invested in renewable energy projects.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("INTC unveiled its next-generation processors.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    ("CVX expanded its natural gas operations.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("NKE launched a sustainable product line.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("MCD introduced plant-based menu options.", {"entities": [(0, 3, "STOCK_SYMBOL")]}),
    ("SBUX opened its first carbon-neutral store.", {"entities": [(0, 4, "STOCK_SYMBOL")]}),
    
    ("The price-to-earnings ratio indicates stock valuation.", {"entities": [(4, 26, "FINANCIAL_METRIC")]}),
    ("EBITDA grew by 15% in the last quarter.", {"entities": [(0, 6, "FINANCIAL_METRIC")]}),
    ("Return on equity exceeded investor expectations.", {"entities": [(0, 16, "FINANCIAL_METRIC")]}),
    ("Free cash flow enabled additional share repurchases.", {"entities": [(0, 14, "FINANCIAL_METRIC")]}),
    ("The debt-to-equity ratio improved after refinancing.", {"entities": [(4, 23, "FINANCIAL_METRIC")]}),
    ("Gross margin expanded to 42% despite rising costs.", {"entities": [(0, 12, "FINANCIAL_METRIC")]}),
    ("Revenue growth accelerated to 12% year-over-year.", {"entities": [(0, 14, "FINANCIAL_METRIC")]}),
    ("Operating income reached a record $2.3 billion.", {"entities": [(0, 16, "FINANCIAL_METRIC")]}),
    ("The current ratio indicates strong liquidity.", {"entities": [(4, 17, "FINANCIAL_METRIC")]}),
    ("Earnings per share beat analyst estimates by 10%.", {"entities": [(0, 18, "FINANCIAL_METRIC")]}),
    ("Net profit margin contracted due to inflation.", {"entities": [(0, 17, "FINANCIAL_METRIC")]}),
    ("Return on assets remained stable at 8.5%.", {"entities": [(0, 16, "FINANCIAL_METRIC")]}),
    ("The quick ratio shows the company's immediate liquidity.", {"entities": [(4, 15, "FINANCIAL_METRIC")]}),
    ("Dividend yield attracted income-focused investors.", {"entities": [(0, 14, "FINANCIAL_METRIC")]}),
    ("Book value per share increased after the stock buyback.", {"entities": [(0, 19, "FINANCIAL_METRIC")]}),
    ("Market capitalization exceeded $1 trillion.", {"entities": [(0, 21, "FINANCIAL_METRIC")]}),
    ("The price-to-book ratio indicated undervaluation.", {"entities": [(4, 22, "FINANCIAL_METRIC")]}),
    ("Days sales outstanding improved to 32 days.", {"entities": [(0, 22, "FINANCIAL_METRIC")]}),
    ("Inventory turnover accelerated in the fourth quarter.", {"entities": [(0, 18, "FINANCIAL_METRIC")]}),
    ("Operating margin expanded despite supply chain challenges.", {"entities": [(0, 16, "FINANCIAL_METRIC")]}),
    
    ("JPMorgan Chase increased its mortgage lending.", {"entities": [(0, 14, "BANK")]}),
    ("Bank of America introduced new digital banking services.", {"entities": [(0, 15, "BANK")]}),
    ("Citigroup announced a restructuring of its global operations.", {"entities": [(0, 9, "BANK")]}),
    ("Wells Fargo faced regulatory penalties for compliance failures.", {"entities": [(0, 11, "BANK")]}),
    ("Goldman Sachs reported record investment banking revenue.", {"entities": [(0, 13, "BANK")]}),
    ("Morgan Stanley expanded its wealth management division.", {"entities": [(0, 14, "BANK")]}),
    ("HSBC focused on its Asian markets for growth.", {"entities": [(0, 4, "BANK")]}),
    ("Deutsche Bank implemented cost-cutting measures.", {"entities": [(0, 13, "BANK")]}),
    ("Barclays increased its technology investments.", {"entities": [(0, 8, "BANK")]}),
    ("Credit Suisse faced losses from hedge fund exposure.", {"entities": [(0, 13, "BANK")]}),
    ("UBS acquired wealth management assets from competitors.", {"entities": [(0, 3, "BANK")]}),
    ("Santander expanded its Latin American operations.", {"entities": [(0, 9, "BANK")]}),
    ("BNP Paribas strengthened its corporate banking services.", {"entities": [(0, 11, "BANK")]}),
    ("Royal Bank of Canada reported strong quarterly earnings.", {"entities": [(0, 23, "BANK")]}),
    ("Société Générale restructured its investment banking division.", {"entities": [(0, 18, "BANK")]}),
    ("Bank of China expanded its international presence.", {"entities": [(0, 13, "BANK")]}),
    ("Standard Chartered focused on emerging markets.", {"entities": [(0, 19, "BANK")]}),
    ("Mitsubishi UFJ Financial Group invested in fintech startups.", {"entities": [(0, 33, "BANK")]}),
    ("Lloyds Banking Group increased mortgage lending rates.", {"entities": [(0, 22, "BANK")]}),
    ("Commerzbank announced a digital transformation strategy.", {"entities": [(0, 12, "BANK")]}),
    
    ("Quantitative easing was implemented to stimulate growth.", {"entities": [(0, 19, "ECONOMIC_POLICY")]}),
    ("Fiscal stimulus packages supported businesses during the pandemic.", {"entities": [(0, 16, "ECONOMIC_POLICY")]}),
    ("Austerity measures reduced government spending.", {"entities": [(0, 17, "ECONOMIC_POLICY")]}),
    ("Supply-side economics influenced tax policies in the 1980s.", {"entities": [(0, 22, "ECONOMIC_POLICY")]}),
    ("Income redistribution aims to reduce economic inequality.", {"entities": [(0, 21, "ECONOMIC_POLICY")]}),
    ("Monetary tightening slowed inflation but impacted growth.", {"entities": [(0, 19, "ECONOMIC_POLICY")]}),
    ("Protectionist policies raised import tariffs on foreign goods.", {"entities": [(0, 21, "ECONOMIC_POLICY")]}),
    ("Full employment became a central economic goal.", {"entities": [(0, 16, "ECONOMIC_POLICY")]}),
    ("Price controls were implemented during the energy crisis.", {"entities": [(0, 14, "ECONOMIC_POLICY")]}),
    ("Deregulation removed government restrictions on industries.", {"entities": [(0, 12, "ECONOMIC_POLICY")]}),
    ("Currency devaluation boosted export competitiveness.", {"entities": [(0, 20, "ECONOMIC_POLICY")]}),
    ("Wage and price freezes attempted to control inflation.", {"entities": [(0, 21, "ECONOMIC_POLICY")]}),
    ("Privatization transferred state-owned enterprises to private ownership.", {"entities": [(0, 13, "ECONOMIC_POLICY")]}),
    ("Industrial policy targeted strategic sector development.", {"entities": [(0, 17, "ECONOMIC_POLICY")]}),
    ("Capital controls limited international money flows.", {"entities": [(0, 16, "ECONOMIC_POLICY")]}),
    ("Negative interest rates stimulated lending in some economies.", {"entities": [(0, 22, "ECONOMIC_POLICY")]}),
    ("Export promotion strategies focused on international market access.", {"entities": [(0, 18, "ECONOMIC_POLICY")]}),
    ("Structural adjustment programs were conditions for IMF loans.", {"entities": [(0, 29, "ECONOMIC_POLICY")]}),
    ("Foreign exchange intervention stabilized currency values.", {"entities": [(0, 29, "ECONOMIC_POLICY")]}),
    ("Labor market reforms modified employment regulations.", {"entities": [(0, 20, "ECONOMIC_POLICY")]}),
    
    ("Progressive taxation increases rates for higher incomes.", {"entities": [(0, 20, "TAX_POLICY")]}),
    ("Capital gains tax applies to investment profits.", {"entities": [(0, 17, "TAX_POLICY")]}),
    ("Estate tax targets wealth transfers after death.", {"entities": [(0, 10, "TAX_POLICY")]}),
    ("Flat tax proposals simplify the tax code.", {"entities": [(0, 8, "TAX_POLICY")]}),
    ("Value-added tax is applied at each production stage.", {"entities": [(0, 17, "TAX_POLICY")]}),
    ("Corporate tax rates vary across countries.", {"entities": [(0, 14, "TAX_POLICY")]}),
    ("Property tax funds local government services.", {"entities": [(0, 12, "TAX_POLICY")]}),
    ("Sales tax rates differ by state and municipality.", {"entities": [(0, 9, "TAX_POLICY")]}),
    ("Wealth tax targets high-net-worth individuals.", {"entities": [(0, 10, "TAX_POLICY")]}),
    ("Excise tax applies to specific goods like alcohol and tobacco.", {"entities": [(0, 10, "TAX_POLICY")]}),
    ("Payroll tax funds social security and Medicare.", {"entities": [(0, 11, "TAX_POLICY")]}),
    ("Carbon tax aims to reduce greenhouse gas emissions.", {"entities": [(0, 10, "TAX_POLICY")]}),
    ("Tax credits reduce tax liability dollar-for-dollar.", {"entities": [(0, 11, "TAX_POLICY")]}),
    ("Tax deductions reduce taxable income.", {"entities": [(0, 15, "TAX_POLICY")]}),
    ("Alternative Minimum Tax prevents excessive tax avoidance.", {"entities": [(0, 24, "TAX_POLICY")]}),
    ("Dividend tax applies to company profit distributions.", {"entities": [(0, 12, "TAX_POLICY")]}),
    ("Inheritance tax is paid by those receiving assets.", {"entities": [(0, 16, "TAX_POLICY")]}),
    ("Gift tax applies to property transfers while alive.", {"entities": [(0, 8, "TAX_POLICY")]}),
    ("Luxury tax targets high-end goods and services.", {"entities": [(0, 10, "TAX_POLICY")]}),
    ("Tax exemptions exclude certain income from taxation.", {"entities": [(0, 14, "TAX_POLICY")]}),
    
    ("NAFTA was replaced by the USMCA in 2020.", {"entities": [(0, 5, "TRADE_AGREEMENT")]}),
    ("The Trans-Pacific Partnership proceeded without US participation.", {"entities": [(4, 32, "TRADE_AGREEMENT")]}),
    ("RCEP became the world's largest trade agreement.", {"entities": [(0, 4, "TRADE_AGREEMENT")]}),
    ("The European Union established a single market.", {"entities": [(4, 18, "TRADE_AGREEMENT")]}),
    ("MERCOSUR facilitated trade among South American countries.", {"entities": [(0, 8, "TRADE_AGREEMENT")]}),
    ("CPTPP was signed after US withdrawal from TPP.", {"entities": [(0, 5, "TRADE_AGREEMENT")]}),
    ("ASEAN promoted economic integration in Southeast Asia.", {"entities": [(0, 5, "TRADE_AGREEMENT")]}),
    ("The US-China Phase One Deal addressed trade disputes.", {"entities": [(4, 27, "TRADE_AGREEMENT")]}),
    ("CAFTA-DR expanded trade between the US and Central America.", {"entities": [(0, 8, "TRADE_AGREEMENT")]}),
    ("The WTO provides a framework for international trade.", {"entities": [(4, 7, "TRADE_AGREEMENT")]}),
    ("AfCFTA created a continent-wide African free trade area.", {"entities": [(0, 6, "TRADE_AGREEMENT")]}),
    ("EFTA established free trade among non-EU European countries.", {"entities": [(0, 4, "TRADE_AGREEMENT")]}),
    ("The US-Korea Free Trade Agreement eliminated most tariffs.", {"entities": [(4, 33, "TRADE_AGREEMENT")]}),
    ("COMESA promoted trade among Eastern and Southern African nations.", {"entities": [(0, 6, "TRADE_AGREEMENT")]}),
    ("The EU-Japan Economic Partnership Agreement reduced trade barriers.", {"entities": [(4, 41, "TRADE_AGREEMENT")]}),
    ("ECOWAS facilitated economic integration in West Africa.", {"entities": [(0, 6, "TRADE_AGREEMENT")]}),
    ("The CETA agreement expanded EU-Canada trade relations.", {"entities": [(4, 20, "TRADE_AGREEMENT")]}),
    ("SAFTA reduced tariffs among South Asian countries.", {"entities": [(0, 5, "TRADE_AGREEMENT")]}),
    ("The USMCA modernized North American trade rules.", {"entities": [(4, 9, "TRADE_AGREEMENT")]}),
    ("GCC Customs Union eliminated tariffs between Gulf states.", {"entities": [(0, 17, "TRADE_AGREEMENT")]}),
    
    ("Commercial real estate values declined in urban centers.", {"entities": [(0, 21, "REAL_ESTATE")]}),
    ("Residential property prices increased in suburban areas.", {"entities": [(0, 20, "REAL_ESTATE")]}),
    ("Office space demand decreased with remote work trends.", {"entities": [(0, 12, "REAL_ESTATE")]}),
    ("Industrial warehouses saw increased occupancy rates.", {"entities": [(0, 21, "REAL_ESTATE")]}),
    ("Retail storefronts faced high vacancy rates.", {"entities": [(0, 17, "REAL_ESTATE")]}),
    ("Luxury condominiums attracted foreign investors.", {"entities": [(0, 18, "REAL_ESTATE")]}),
    ("Affordable housing projects received government funding.", {"entities": [(0, 18, "REAL_ESTATE")]}),
    ("Single-family homes experienced price appreciation.", {"entities": [(0, 18, "REAL_ESTATE")]}),
    ("Multi-family apartments showed strong rental yields.", {"entities": [(0, 22, "REAL_ESTATE")]}),
    ("Mixed-use developments combined residential and commercial spaces.", {"entities": [(0, 21, "REAL_ESTATE")]}),
    ("Data centers became a high-growth real estate sector.", {"entities": [(0, 12, "REAL_ESTATE")]}),
    ("Healthcare facilities expanded to meet demographic needs.", {"entities": [(0, 19, "REAL_ESTATE")]}),
    ("Student housing occupancy decreased during the pandemic.", {"entities": [(0, 15, "REAL_ESTATE")]}),
    ("Senior living communities adapted to new safety protocols.", {"entities": [(0, 24, "REAL_ESTATE")]}),
    ("Self-storage facilities reported high occupancy rates.", {"entities": [(0, 23, "REAL_ESTATE")]}),
    ("Hospitality properties struggled with travel restrictions.", {"entities": [(0, 21, "REAL_ESTATE")]}),
    ("Agricultural land values increased with food security concerns.", {"entities": [(0, 17, "REAL_ESTATE")]}),
    ("Co-working spaces reinvented their business models.", {"entities": [(0, 17, "REAL_ESTATE")]}),
    ("Historic buildings underwent preservation and repurposing.", {"entities": [(0, 17, "REAL_ESTATE")]}),
    ("Vacation rentals recovered as travel restrictions eased.", {"entities": [(0, 16, "REAL_ESTATE")]}),
    
    ("Mortgage loans became more affordable with lower rates.", {"entities": [(0, 14, "LOAN")]}),
    ("Personal loans helped consolidate higher-interest debt.", {"entities": [(0, 14, "LOAN")]}),
    ("Auto loans facilitated vehicle purchases.", {"entities": [(0, 10, "LOAN")]}),
    ("Student loans total over $1.7 trillion in the US.", {"entities": [(0, 13, "LOAN")]}),
    ("Business loans supported small enterprises during the crisis.", {"entities": [(0, 14, "LOAN")]}),
    ("Home equity loans utilized property value for financing.", {"entities": [(0, 17, "LOAN")]}),
    ("Payday loans charge high interest rates for short-term borrowing.", {"entities": [(0, 12, "LOAN")]}),
    ("Construction loans financed new building projects.", {"entities": [(0, 17, "LOAN")]}),
    ("Credit card loans accumulated during the economic downturn.", {"entities": [(0, 17, "LOAN")]}),
    ("Refinancing loans reduced monthly payment obligations.", {"entities": [(0, 17, "LOAN")]}),
    ("Peer-to-peer loans connected borrowers directly with lenders.", {"entities": [(0, 18, "LOAN")]}),
    ("Debt consolidation loans combined multiple obligations.", {"entities": [(0, 25, "LOAN")]}),
    ("Installment loans provided structured repayment plans.", {"entities": [(0, 17, "LOAN")]}),
    ("Bridge loans facilitated property transitions.", {"entities": [(0, 12, "LOAN")]}),
    ("Commercial loans funded business expansion projects.", {"entities": [(0, 16, "LOAN")]}),
    ("Agricultural loans supported farmers' seasonal needs.", {"entities": [(0, 18, "LOAN")]}),
    ("Government-backed loans offered favorable terms for qualified borrowers.", {"entities": [(0, 23, "LOAN")]}),
    ("Microloans provided capital for small entrepreneurs.", {"entities": [(0, 10, "LOAN")]}),
    ("Line of credit loans offered flexible access to funds.", {"entities": [(0, 19, "LOAN")]}),
    ("Hard money loans secured financing based on property value.", {"entities": [(0, 16, "LOAN")]}),
    
    ("Crude oil prices fluctuated due to production decisions.", {"entities": [(0, 9, "COMMODITY")]}),
    ("Gold served as a haven during economic uncertainty.", {"entities": [(0, 4, "COMMODITY")]}),
    ("Natural gas demand increased during the cold winter.", {"entities": [(0, 11, "COMMODITY")]}),
    ("Corn prices rose due to drought conditions.", {"entities": [(0, 4, "COMMODITY")]}),
    ("Silver attracted both industrial and investment demand.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Wheat exports faced logistical challenges.", {"entities": [(0, 5, "COMMODITY")]}),
    ("Copper prices indicated strong manufacturing activity.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Soybeans experienced increased Chinese demand.", {"entities": [(0, 8, "COMMODITY")]}),
    ("Cotton production decreased due to adverse weather.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Iron ore shipments to steel producers increased.", {"entities": [(0, 8, "COMMODITY")]}),
    ("Coffee prices surged after frost damaged Brazilian crops.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Aluminum production costs rose with energy prices.", {"entities": [(0, 8, "COMMODITY")]}),
    ("Sugar supplies tightened amid production shortfalls.", {"entities": [(0, 5, "COMMODITY")]}),
    ("Platinum demand grew with automotive production recovery.", {"entities": [(0, 8, "COMMODITY")]}),
    ("Cattle prices fluctuated due to feed cost changes.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Lumber prices reached record highs during construction boom.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Nickel is essential for electric vehicle batteries.", {"entities": [(0, 6, "COMMODITY")]}),
    ("Palladium shortages affected automotive manufacturers.", {"entities": [(0, 9, "COMMODITY")]}),
    ("Rice exports increased from Asian producers.", {"entities": [(0, 4, "COMMODITY")]}),
    ("Cobalt demand grew with battery technology adoption.", {"entities": [(0, 6, "COMMODITY")]}),
    
    ("Federal funds rate influences interbank lending.", {"entities": [(0, 18, "INTEREST_RATE")]}),
    ("Prime rate affects consumer and business loans.", {"entities": [(0, 10, "INTEREST_RATE")]}),
    ("LIBOR phaseout required alternative benchmark rates.", {"entities": [(0, 5, "INTEREST_RATE")]}),
    ("Mortgage rates reached historic lows last year.", {"entities": [(0, 14, "INTEREST_RATE")]}),
    ("Treasury yields reflect government borrowing costs.", {"entities": [(0, 14, "INTEREST_RATE")]}),
    ("Discount rate is set by the Federal Reserve for bank borrowing.", {"entities": [(0, 13, "INTEREST_RATE")]}),
    ("SOFR replaced LIBOR for many financial contracts.", {"entities": [(0, 4, "INTEREST_RATE")]}),
    ("CD rates offer guaranteed returns for savers.", {"entities": [(0, 8, "INTEREST_RATE")]}),
    ("Corporate bond yields vary based on credit risk.", {"entities": [(0, 21, "INTEREST_RATE")]}),
    ("Savings account rates remained near zero.", {"entities": [(0, 21, "INTEREST_RATE")]}),
    ("EURIBOR serves as a benchmark for eurozone loans.", {"entities": [(0, 7, "INTEREST_RATE")]}),
    ("Repo rate provides short-term liquidity to banks.", {"entities": [(0, 9, "INTEREST_RATE")]}),
    ("Overnight rate influences short-term borrowing costs.", {"entities": [(0, 14, "INTEREST_RATE")]}),
    ("Municipal bond yields attract tax-conscious investors.", {"entities": [(0, 20, "INTEREST_RATE")]}),
    ("High-yield bond rates compensate for greater default risk.", {"entities": [(0, 19, "INTEREST_RATE")]}),
    ("Student loan rates are set annually by Congress.", {"entities": [(0, 17, "INTEREST_RATE")]}),
    ("APR includes both interest and fees on loans.", {"entities": [(0, 3, "INTEREST_RATE")]}),
    ("Benchmark rate changes affect variable-rate loans.", {"entities": [(0, 14, "INTEREST_RATE")]}),
    ("Real interest rates account for inflation effects.", {"entities": [(0, 19, "INTEREST_RATE")]}),
    ("Negative interest rates were implemented by some central banks.", {"entities": [(0, 23, "INTEREST_RATE")]}),
    
    ("COVID-19 spread globally in early 2020.", {"entities": [(0, 8, "DISEASE")]}),
    ("Diabetes affects millions of people worldwide.", {"entities": [(0, 8, "DISEASE")]}),
    ("Alzheimer's disease progressively affects cognitive function.", {"entities": [(0, 19, "DISEASE")]}),
    ("Malaria remains prevalent in tropical regions.", {"entities": [(0, 7, "DISEASE")]}),
    ("Tuberculosis requires extended antibiotic treatment.", {"entities": [(0, 12, "DISEASE")]}),
    ("Heart disease is a leading cause of death globally.", {"entities": [(0, 13, "DISEASE")]}),
    ("Cancer research focuses on early detection methods.", {"entities": [(0, 6, "DISEASE")]}),
    ("Parkinson's disease affects movement and coordination.", {"entities": [(0, 18, "DISEASE")]}),
    ("HIV/AIDS treatment has improved life expectancy.", {"entities": [(0, 8, "DISEASE")]}),
    ("Influenza viruses mutate rapidly each season.", {"entities": [(0, 9, "DISEASE")]}),
    ("Hepatitis infections affect liver function.", {"entities": [(0, 9, "DISEASE")]}),
    ("Asthma symptoms worsen with poor air quality.", {"entities": [(0, 6, "DISEASE")]}),
    ("Ebola outbreaks require strict containment measures.", {"entities": [(0, 5, "DISEASE")]}),
    ("Multiple sclerosis affects the central nervous system.", {"entities": [(0, 18, "DISEASE")]}),
    ("Arthritis causes joint pain and inflammation.", {"entities": [(0, 9, "DISEASE")]}),
    ("Cystic fibrosis affects respiratory and digestive systems.", {"entities": [(0, 15, "DISEASE")]}),
    ("Stroke requires immediate medical intervention.", {"entities": [(0, 6, "DISEASE")]}),
    ("COPD progressively limits airflow to the lungs.", {"entities": [(0, 4, "DISEASE")]}),
    ("Hypertension increases risk for heart disease and stroke.", {"entities": [(0, 12, "DISEASE")]}),
    ("Autism spectrum disorder varies widely in its presentation.", {"entities": [(0, 24, "DISEASE")]}),
    
    ("Aspirin reduces inflammation and prevents blood clots.", {"entities": [(0, 7, "DRUG")]}),
    ("Insulin regulates blood glucose levels in diabetic patients.", {"entities": [(0, 7, "DRUG")]}),
    ("Lipitor lowers cholesterol levels effectively.", {"entities": [(0, 7, "DRUG")]}),
    ("Penicillin revolutionized bacterial infection treatment.", {"entities": [(0, 10, "DRUG")]}),
    ("Remdesivir was used to treat severe COVID-19 cases.", {"entities": [(0, 10, "DRUG")]}),
    ("Prozac treats depression and anxiety disorders.", {"entities": [(0, 6, "DRUG")]}),
    ("Advil relieves pain and reduces inflammation.", {"entities": [(0, 5, "DRUG")]}),
    ("Metformin is a first-line treatment for type 2 diabetes.", {"entities": [(0, 9, "DRUG")]}),
    ("Adderall treats attention deficit hyperactivity disorder.", {"entities": [(0, 8, "DRUG")]}),
    ("Humira treats rheumatoid arthritis and other inflammatory conditions.", {"entities": [(0, 6, "DRUG")]}),
    ("Ozempic helps manage blood sugar and supports weight loss.", {"entities": [(0, 7, "DRUG")]}),
    ("Lexapro treats depression and generalized anxiety disorder.", {"entities": [(0, 7, "DRUG")]}),
    ("Synthroid treats hypothyroidism by replacing thyroid hormone.", {"entities": [(0, 9, "DRUG")]}),
    ("Morphine provides pain relief for severe conditions.", {"entities": [(0, 8, "DRUG")]}),
    ("Xanax treats anxiety and panic disorders.", {"entities": [(0, 5, "DRUG")]}),
    ("Tamiflu reduces the severity of influenza symptoms.", {"entities": [(0, 7, "DRUG")]}),
    ("Paxlovid reduced COVID-19 hospitalization rates.", {"entities": [(0, 8, "DRUG")]}),
    ("Ibuprofen reduces pain, inflammation, and fever.", {"entities": [(0, 9, "DRUG")]}),
    ("Januvia helps manage type 2 diabetes blood sugar levels.", {"entities": [(0, 7, "DRUG")]}),
    ("Lisinopril treats high blood pressure and heart failure.", {"entities": [(0, 10, "DRUG")]}),
    
    ("Fever indicates an immune response to infection.", {"entities": [(0, 5, "SYMPTOM")]}),
    ("Cough can be a symptom of respiratory infections.", {"entities": [(0, 5, "SYMPTOM")]}),
    ("Fatigue is common in many medical conditions.", {"entities": [(0, 7, "SYMPTOM")]}),
    ("Headache may indicate stress or underlying conditions.", {"entities": [(0, 8, "SYMPTOM")]}),
    ("Nausea often accompanies digestive disorders.", {"entities": [(0, 6, "SYMPTOM")]}),
    ("Shortness of breath requires immediate medical attention.", {"entities": [(0, 19, "SYMPTOM")]}),
    ("Chest pain could indicate cardiovascular issues.", {"entities": [(0, 10, "SYMPTOM")]}),
    ("Dizziness may result from inner ear problems or low blood pressure.", {"entities": [(0, 9, "SYMPTOM")]}),
    ("Rash may indicate an allergic reaction or infection.", {"entities": [(0, 4, "SYMPTOM")]}),
    ("Joint pain is a common symptom of arthritis.", {"entities": [(0, 10, "SYMPTOM")]}),
    ("Muscle weakness can indicate neurological conditions.", {"entities": [(0, 15, "SYMPTOM")]}),
    ("Abdominal pain has many potential causes.", {"entities": [(0, 14, "SYMPTOM")]}),
    ("Vomiting can lead to dehydration if persistent.", {"entities": [(0, 8, "SYMPTOM")]}),
    ("Sore throat often occurs with upper respiratory infections.", {"entities": [(0, 11, "SYMPTOM")]}),
    ("Blurred vision may indicate eye problems or neurological issues.", {"entities": [(0, 14, "SYMPTOM")]}),
    ("Swelling can result from inflammation or fluid retention.", {"entities": [(0, 8, "SYMPTOM")]}),
    ("Numbness might indicate nerve compression or damage.", {"entities": [(0, 8, "SYMPTOM")]}),
    ("Insomnia affects overall health and cognitive function.", {"entities": [(0, 8, "SYMPTOM")]}),
    ("Loss of appetite can lead to malnutrition if prolonged.", {"entities": [(0, 16, "SYMPTOM")]}),
    ("Back pain affects millions of people worldwide.", {"entities": [(0, 9, "SYMPTOM")]}),
    
    ("Chemotherapy targets rapidly dividing cancer cells.", {"entities": [(0, 12, "TREATMENT")]}),
    ("Physical therapy improves mobility and function.", {"entities": [(0, 16, "TREATMENT")]}),
    ("Radiation therapy uses high-energy particles to destroy tumors.", {"entities": [(0, 17, "TREATMENT")]}),
    ("Cognitive behavioral therapy treats various mental health conditions.", {"entities": [(0, 28, "TREATMENT")]}),
    ("Dialysis filters blood when kidneys aren't functioning properly.", {"entities": [(0, 8, "TREATMENT")]}),
    ("Surgery removes or repairs damaged tissues and organs.", {"entities": [(0, 7, "TREATMENT")]}),
    ("Immunotherapy harnesses the body's immune system to fight disease.", {"entities": [(0, 14, "TREATMENT")]}),
    ("Gene therapy corrects defective genes to treat hereditary conditions.", {"entities": [(0, 12, "TREATMENT")]}),
    ("Hormone replacement therapy addresses endocrine deficiencies.", {"entities": [(0, 29, "TREATMENT")]}),
    ("Antibiotic treatment targets bacterial infections.", {"entities": [(0, 20, "TREATMENT")]}),
    ("Stem cell therapy shows promise for regenerative medicine.", {"entities": [(0, 17, "TREATMENT")]}),
    ("Psychotherapy addresses psychological and emotional difficulties.", {"entities": [(0, 13, "TREATMENT")]}),
    ("Oxygen therapy supplements insufficient natural breathing.", {"entities": [(0, 14, "TREATMENT")]}),
    ("Antiviral treatment reduces viral replication in infected cells.", {"entities": [(0, 19, "TREATMENT")]}),
    ("Acupuncture uses needles to stimulate specific body points.", {"entities": [(0, 11, "TREATMENT")]}),
    ("Pain management combines medications and therapies.", {"entities": [(0, 15, "TREATMENT")]}),
    ("Blood transfusion replaces lost blood components.", {"entities": [(0, 17, "TREATMENT")]}),
    ("Rehabilitation helps restore function after injury or illness.", {"entities": [(0, 14, "TREATMENT")]}),
    ("Palliative care focuses on improving quality of life.", {"entities": [(0, 15, "TREATMENT")]}),
    ("Speech therapy addresses communication and swallowing disorders.", {"entities": [(0, 14, "TREATMENT")]}),
    
    ("MMR vaccine protects against measles, mumps, and rubella.", {"entities": [(0, 11, "VACCINE")]}),
    ("Pfizer-BioNTech COVID-19 vaccine used mRNA technology.", {"entities": [(0, 35, "VACCINE")]}),
    ("Flu vaccine is reformulated annually for new strains.", {"entities": [(0, 11, "VACCINE")]}),
    ("HPV vaccine prevents human papillomavirus infections.", {"entities": [(0, 11, "VACCINE")]}),
    ("Polio vaccine eradicated the disease in most countries.", {"entities": [(0, 13, "VACCINE")]}),
    ("Moderna COVID-19 vaccine showed high efficacy rates.", {"entities": [(0, 26, "VACCINE")]}),
    ("Hepatitis B vaccine is given in a three-dose series.", {"entities": [(0, 18, "VACCINE")]}),
    ("DTaP vaccine protects against diphtheria, tetanus, and pertussis.", {"entities": [(0, 12, "VACCINE")]}),
    ("Tetanus vaccine requires boosters every ten years.", {"entities": [(0, 15, "VACCINE")]}),
    ("Pneumococcal vaccine prevents serious bacterial infections.", {"entities": [(0, 20, "VACCINE")]}),
    ("Shingles vaccine reduces risk and severity of herpes zoster.", {"entities": [(0, 16, "VACCINE")]}),
    ("Chickenpox vaccine prevents varicella virus infection.", {"entities": [(0, 18, "VACCINE")]}),
    ("Johnson & Johnson COVID-19 vaccine required only one dose.", {"entities": [(0, 37, "VACCINE")]}),
    ("Yellow fever vaccine is required for travel to certain regions.", {"entities": [(0, 19, "VACCINE")]}),
    ("Rotavirus vaccine prevents severe diarrhea in infants.", {"entities": [(0, 17, "VACCINE")]}),
    ("Meningococcal vaccine protects against bacterial meningitis.", {"entities": [(0, 21, "VACCINE")]}),
    ("Typhoid vaccine reduces risk for travelers to endemic areas.", {"entities": [(0, 15, "VACCINE")]}),
    ("Rabies vaccine is administered after potential exposure.", {"entities": [(0, 14, "VACCINE")]}),
    ("BCG vaccine protects against tuberculosis in high-risk areas.", {"entities": [(0, 11, "VACCINE")]}),
    ("Novavax COVID-19 vaccine uses protein-based technology.", {"entities": [(0, 26, "VACCINE")]}),
    
    ("Mayo Clinic ranks among the top healthcare facilities.", {"entities": [(0, 11, "HOSPITAL")]}),
    ("Johns Hopkins Hospital pioneered many medical innovations.", {"entities": [(0, 24, "HOSPITAL")]}),
    ("Cleveland Clinic specializes in cardiovascular care.", {"entities": [(0, 16, "HOSPITAL")]}),
    ("Massachusetts General Hospital treats complex medical cases.", {"entities": [(0, 31, "HOSPITAL")]}),
    ("Cedars-Sinai Medical Center expanded its oncology department.", {"entities": [(0, 28, "HOSPITAL")]}),
    ("New York-Presbyterian Hospital serves the metropolitan area.", {"entities": [(0, 32, "HOSPITAL")]}),
    ("Stanford Hospital implements advanced medical technologies.", {"entities": [(0, 17, "HOSPITAL")]}),
    ("UCLA Medical Center excels in organ transplantation.", {"entities": [(0, 19, "HOSPITAL")]}),
    ("UCSF Medical Center specializes in neurosurgery.", {"entities": [(0, 19, "HOSPITAL")]}),
    ("Brigham and Women's Hospital conducts pioneering research.", {"entities": [(0, 29, "HOSPITAL")]}),
    ("MD Anderson Cancer Center leads in oncology treatment.", {"entities": [(0, 26, "HOSPITAL")]}),
    ("Mount Sinai Hospital implemented new patient care protocols.", {"entities": [(0, 20, "HOSPITAL")]}),
    ("Memorial Sloan Kettering focuses on cancer treatment.", {"entities": [(0, 27, "HOSPITAL")]}),
    ("Northwestern Memorial Hospital expanded emergency services.", {"entities": [(0, 32, "HOSPITAL")]}),
    ("Barnes-Jewish Hospital serves the St. Louis region.", {"entities": [(0, 23, "HOSPITAL")]}),
    ("NYU Langone Health opened a new pediatric center.", {"entities": [(0, 18, "HOSPITAL")]}),
    ("Duke University Hospital trains medical professionals.", {"entities": [(0, 24, "HOSPITAL")]}),
    ("Vanderbilt University Medical Center employs over 30,000 people.", {"entities": [(0, 35, "HOSPITAL")]}),
    ("University of Michigan Hospital specializes in transplantation.", {"entities": [(0, 31, "HOSPITAL")]}),
    ("Tufts Medical Center serves the Boston community.", {"entities": [(0, 19, "HOSPITAL")]}),
    
    ("Pacemakers regulate abnormal heart rhythms.", {"entities": [(0, 10, "MEDICAL_DEVICE")]}),
    ("The police arrested suspects in a fraud case.", {"entities": [(4, 19, "LAW_ENFORCEMENT")]}),
    ("FBI agents investigated the cybercrime ring.", {"entities": [(0, 11, "LAW_ENFORCEMENT")]}),
    ("Local law enforcement responded to the protest.", {"entities": [(6, 21, "LAW_ENFORCEMENT")]}),
    ("Sheriffs patrolled the area during the event.", {"entities": [(0, 8, "LAW_ENFORCEMENT")]}),
    ("The DEA seized drugs in a major operation.", {"entities": [(4, 8, "LAW_ENFORCEMENT")]}),
    ("Police officers managed traffic during the parade.", {"entities": [(0, 14, "LAW_ENFORCEMENT")]}),
    ("State troopers handled the highway accident.", {"entities": [(0, 13, "LAW_ENFORCEMENT")]}),
    ("The FBI launched an inquiry into corruption.", {"entities": [(4, 8, "LAW_ENFORCEMENT")]}),
    ("Local police dealt with the burglary report.", {"entities": [(6, 17, "LAW_ENFORCEMENT")]}),
    ("Sheriffs enforced curfew during the riots.", {"entities": [(0, 8, "LAW_ENFORCEMENT")]}),
    ("The DEA conducted raids on drug labs.", {"entities": [(4, 8, "LAW_ENFORCEMENT")]}),
    ("Police managed crowd control at the rally.", {"entities": [(0, 6, "LAW_ENFORCEMENT")]}),
    ("State troopers investigated the hit-and-run.", {"entities": [(0, 13, "LAW_ENFORCEMENT")]}),
    ("The FBI tracked down the fugitive.", {"entities": [(4, 8, "LAW_ENFORCEMENT")]}),
    ("Local law enforcement arrested the suspect.", {"entities": [(6, 21, "LAW_ENFORCEMENT")]}),
    ("Sheriffs monitored the border area.", {"entities": [(0, 8, "LAW_ENFORCEMENT")]}),
    ("The DEA busted a drug trafficking network.", {"entities": [(4, 8, "LAW_ENFORCEMENT")]}),
    ("Police officers responded to the emergency call.", {"entities": [(0, 14, "LAW_ENFORCEMENT")]}),
    ("State troopers patrolled the highway.", {"entities": [(0, 13, "LAW_ENFORCEMENT")]}),
    ("The FBI investigated the financial fraud.", {"entities": [(4, 8, "LAW_ENFORCEMENT")]}),
    ("The housing initiative launched in February 2025.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A new education program was announced.", {"entities": [(14, 31, "GOVERNMENT_PROGRAM")]}),
    ("The healthcare program expanded to rural areas.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A welfare program supported low-income families.", {"entities": [(2, 19, "GOVERNMENT_PROGRAM")]}),
    ("The job training program started in January.", {"entities": [(4, 22, "GOVERNMENT_PROGRAM")]}),
    ("A new infrastructure program was funded.", {"entities": [(14, 31, "GOVERNMENT_PROGRAM")]}),
    ("The environmental program aimed at conservation.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A health insurance program was introduced.", {"entities": [(2, 19, "GOVERNMENT_PROGRAM")]}),
    ("The education program focused on STEM subjects.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A welfare initiative supported unemployed workers.", {"entities": [(2, 19, "GOVERNMENT_PROGRAM")]}),
    ("The housing program addressed homelessness.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A new job program was launched in 2025.", {"entities": [(14, 31, "GOVERNMENT_PROGRAM")]}),
    ("The healthcare program included mental health services.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A welfare program aided disaster victims.", {"entities": [(2, 19, "GOVERNMENT_PROGRAM")]}),
    ("The education program expanded to rural schools.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A new infrastructure program was debated.", {"entities": [(14, 31, "GOVERNMENT_PROGRAM")]}),
    ("The environmental program focused on clean energy.", {"entities": [(4, 21, "GOVERNMENT_PROGRAM")]}),
    ("A health program addressed chronic diseases.", {"entities": [(2, 19, "GOVERNMENT_PROGRAM")]}),
    ("The job training program saw high enrollment.", {"entities": [(4, 22, "GOVERNMENT_PROGRAM")]}),
    ("A welfare initiative supported veterans.", {"entities": [(2, 19, "GOVERNMENT_PROGRAM")]}),
    ("The company signed a service contract in January.", {"entities": [(24, 38, "CONTRACT_TYPE")]}),
    ("A lease agreement was finalized for the office space.", {"entities": [(2, 16, "CONTRACT_TYPE")]}),
    ("The sales contract was reviewed by legal teams.", {"entities": [(4, 18, "CONTRACT_TYPE")]}),
    ("A partnership agreement was announced in 2025.", {"entities": [(2, 19, "CONTRACT_TYPE")]}),
    ("The employment contract included benefits.", {"entities": [(4, 20, "CONTRACT_TYPE")]}),
    ("A construction contract was awarded to a firm.", {"entities": [(2, 19, "CONTRACT_TYPE")]}),
    ("The licensing agreement covered software use.", {"entities": [(4, 21, "CONTRACT_TYPE")]}),
    ("A franchise agreement was signed last month.", {"entities": [(2, 19, "CONTRACT_TYPE")]}),
    ("The purchase contract was completed in February.", {"entities": [(4, 19, "CONTRACT_TYPE")]}),
    ("A rental agreement was made for the equipment.", {"entities": [(2, 16, "CONTRACT_TYPE")]}),
    ("The service contract ensured maintenance services.", {"entities": [(4, 18, "CONTRACT_TYPE")]}),
    ("A lease contract was negotiated for the property.", {"entities": [(2, 15, "CONTRACT_TYPE")]}),
    ("The sales agreement included delivery terms.", {"entities": [(4, 18, "CONTRACT_TYPE")]}),
    ("A partnership contract was signed with a tech firm.", {"entities": [(2, 19, "CONTRACT_TYPE")]}),
    ("The employment agreement outlined salary details.", {"entities": [(4, 20, "CONTRACT_TYPE")]}),
    ("A construction contract was delayed due to permits.", {"entities": [(2, 19, "CONTRACT_TYPE")]}),
    ("The licensing contract covered intellectual property.", {"entities": [(4, 21, "CONTRACT_TYPE")]}),
    ("A franchise agreement expanded to new regions.", {"entities": [(2, 19, "CONTRACT_TYPE")]}),
    ("The purchase agreement was signed in early 2025.", {"entities": [(4, 19, "CONTRACT_TYPE")]}),
    ("A rental contract was made for the warehouse.", {"entities": [(2, 15, "CONTRACT_TYPE")]}),
    ("Judge Roberts presided over the fraud case.", {"entities": [(0, 12, "JUDGE")]}),
    ("Judge Lee sentenced the defendant to prison.", {"entities": [(0, 9, "JUDGE")]}),
    ("Judge Smith handled the high-profile trial.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Patel issued a ruling on the dispute.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Johnson oversaw the civil lawsuit.", {"entities": [(0, 12, "JUDGE")]}),
    ("Judge Brown dismissed the case due to evidence.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Kim granted a motion for a new trial.", {"entities": [(0, 9, "JUDGE")]}),
    ("Judge Garcia ruled on the copyright issue.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Nguyen heard arguments in the appeal.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Taylor sentenced the criminal to probation.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Evans presided over the bankruptcy case.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Harris issued a summary judgment.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Clark handled the environmental lawsuit.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge White ruled on the contract dispute.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Miller oversaw the criminal trial.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Davis granted an injunction in February.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Wilson dismissed the defamation case.", {"entities": [(0, 11, "JUDGE")]}),
    ("Judge Anderson sentenced the offender to jail.", {"entities": [(0, 12, "JUDGE")]}),
    ("Judge Thompson ruled on the property dispute.", {"entities": [(0, 12, "JUDGE")]}),
    ("Judge Roberts presided over the fraud case again.", {"entities": [(0, 12, "JUDGE")]}),
    ("The suspect faced fraud charges in court.", {"entities": [(19, 31, "CRIMINAL_CHARGE")]}),
    ("He was charged with theft in January 2025.", {"entities": [(14, 20, "CRIMINAL_CHARGE")]}),
    ("The indictment included embezzlement charges.", {"entities": [(24, 40, "CRIMINAL_CHARGE")]}),
    ("She faced assault charges after the incident.", {"entities": [(12, 25, "CRIMINAL_CHARGE")]}),
    ("The defendant was charged with drug trafficking.", {"entities": [(24, 40, "CRIMINAL_CHARGE")]}),
    ("Fraud charges were filed against the CEO.", {"entities": [(0, 13, "CRIMINAL_CHARGE")]}),
    ("He faced burglary charges in early 2025.", {"entities": [(12, 25, "CRIMINAL_CHARGE")]}),
    ("The suspect was charged with money laundering.", {"entities": [(24, 40, "CRIMINAL_CHARGE")]}),
    ("She faced manslaughter charges in court.", {"entities": [(12, 27, "CRIMINAL_CHARGE")]})
]